# General Settings
title: Life in Chist
description: A simple website for sharing resources to live a meaningful Christian life
baseurl: "/LifeInChrist" # the subpath of your site, e.g. /blog

# Theme Settings
theme: jekyll-theme-architect
# jekyll-theme-cayman
# remote_theme: mmistakes/so-simple-theme@3.2.0
# pages-themes/dinky OR pages-themes/minimal OR pages-themes/primer OR pages-themes/slate OR pages-themes/tactile OR pages-themes/time-machine OR pages-themes/leap-day OR pages-themes/modernist
# mmistakes/minimal-mistakes@4.22.0

skin: "/assets/css/skins/default.css"
locale: en-GB

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# GitHub Pages Settings
repository: matteoicardi/LifeInChrist
baseurl: "" # Leave this empty unless using a custom domain

# Build Settings
markdown: kramdown
permalink: pretty

# # Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-avatar
  - jekyll-include-cache
  - jekyll-default-layout
  - jekyll-toc
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-mentions
  
# Navigation Links (optional)
navigation:
  - title: Home
    url: /
  - title: Confirmation
    url: /Confirmation
  - title: Blog
    url: /blog

collections:
  blog:
    output: true
    permalink: /blog/:title
# Any other custom settings or variables can be added as needed
